# Generated by Django 4.1.7 on 2023-09-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_number', models.CharField(max_length=200, unique=True, verbose_name='Number')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('floor', models.IntegerField(null=True)),
                ('length', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('observation_pit', models.BooleanField(null=True)),
                ('build_date', models.DateField(null=True)),
                ('initial_cost', models.FloatField(null=True)),
                ('estimated_cost', models.FloatField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('patronymic', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(null=True, upload_to='photos/%pk')),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('questions', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_part', models.FloatField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('estate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.estate')),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.relationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200, null=True)),
                ('car_color', models.CharField(max_length=200, null=True)),
                ('car_number', models.CharField(max_length=200, null=True)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('relation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.relation')),
            ],
            options={
                'verbose_name_plural': 'Passes',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=200)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.contacttype')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=200, null=True)),
                ('house_number', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
