# Generated by Django 4.1.7 on 2023-09-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_rented',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='is_sold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='relation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.relation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person'),
        ),
    ]
