# Generated by Django 4.1.7 on 2023-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='build_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estimated_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='initial_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='observation_pit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='car_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='car_model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='car_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%pk'),
        ),
        migrations.AlterField(
            model_name='person',
            name='questions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ownership_part',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
