# Generated by Django 4.1.7 on 2023-11-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_contact_contact_type_alter_relation_person_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['region', 'city', 'street', 'house_number', 'flat_number'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_type', 'contact_info'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'verbose_name': 'Тип контакта', 'verbose_name_plural': 'Типы контактов'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Члены кооператива и связанные лица'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Отношение', 'verbose_name_plural': 'Отношения'},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'verbose_name': 'Тип отношения', 'verbose_name_plural': 'Типы отношений'},
        ),
        migrations.AlterField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.contacttype', verbose_name='Тип контактной информации'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='observation_pit',
            field=models.BooleanField(blank=True, choices=[(True, 'Есть'), (False, 'Нет'), (None, '')], null=True, verbose_name='Смотровая яма'),
        ),
    ]
