# Generated by Django 4.1.7 on 2023-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_address_city_alter_address_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='contact_type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='relation_type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
