# Generated by Django 4.1.7 on 2023-11-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_address_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['person_id', 'contact_type', 'contact_info'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'verbose_name': 'Тип отношения к владельцу', 'verbose_name_plural': 'Типы отношений'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.contacttype', verbose_name='Тип контактной информации'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='relation_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.relation', verbose_name='Имеет отношение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Отношение прекращено'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='estate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.estate', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ownership_part',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Доля собственности'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.relationtype', verbose_name='Отношение'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Отношение возникло'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='relation_type',
            field=models.CharField(max_length=200, verbose_name='Тип отношения к владельцу'),
        ),
    ]
