# Generated by Django 4.1.7 on 2023-10-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_address_city_alter_address_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='initial_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
