# Generated by Django 4.1.7 on 2023-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_estate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': [models.Value(0, output_field=models.IntegerField()), 'estate_number'], 'verbose_name': 'Estate', 'verbose_name_plural': 'Estates'},
        ),
    ]
