# Generated by Django 4.1.7 on 2023-10-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_estate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Estate', 'verbose_name_plural': 'Estates'},
        ),
    ]
