# Generated by Django 4.1.7 on 2023-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_estate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='is_rented',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='estate',
            name='estimated_cost_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оценки'),
        ),
        migrations.AddField(
            model_name='estate',
            name='for_rent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сдается в аренду'),
        ),
        migrations.AddField(
            model_name='estate',
            name='for_sale',
            field=models.BooleanField(blank=True, null=True, verbose_name='Продается'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='build_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постройки'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Оценочная стоимость'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='initial_cost',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Начальная стоимость'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='observation_pit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Смотровая яма'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Данные обновлены'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
