# Generated by Django 4.1.7 on 2023-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_estate_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name_plural': 'Personalities'},
        ),
        migrations.AlterField(
            model_name='estate',
            name='for_rent',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, '')], null=True, verbose_name='Сдается в аренду'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='for_sale',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, '')], null=True, verbose_name='Продается'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='observation_pit',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, '')], null=True, verbose_name='Смотровая яма'),
        ),
    ]
