# Generated by Django 4.1.7 on 2023-10-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_person_options_alter_estate_for_rent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personalities'},
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Данные обновлены'),
        ),
    ]
