# Generated by Django 4.1.7 on 2023-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_person_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'street', 'house_number', 'flat_number'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Область, район'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Данные обновлены'),
        ),
    ]
